# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0005_modelbase_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
                ('markdown', models.TextField(blank=True, null=True)),
                ('layout', models.CharField(choices=[(b'detail', b'Detail view')], default=b'plain', help_text=b'The layout of this block', max_length=50)),
                ('extra_classes', models.CharField(blank=True, help_text=b'Extra css classes to apply to the block.            Separate with spaces.', max_length=150)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
            },
            bases=('jmbo.modelbase',),
        ),
    ]
