# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20160902_0249'),
        ('contentblocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.Link'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='markdown',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True),
        ),
    ]
